
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 12 18:42:05 IST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int LCBR = 24;
  public static final int LTE = 16;
  public static final int INTEGER = 45;
  public static final int CONTINUE = 38;
  public static final int SEMI = 2;
  public static final int INT = 30;
  public static final int MINUS = 6;
  public static final int STATIC = 28;
  public static final int LT = 14;
  public static final int LP = 22;
  public static final int COMMA = 4;
  public static final int CLASS = 26;
  public static final int RP = 23;
  public static final int PLUS = 5;
  public static final int MULTIPLY = 7;
  public static final int QUOTE = 46;
  public static final int ASSIGN = 10;
  public static final int IF = 34;
  public static final int THIS = 39;
  public static final int ID = 47;
  public static final int DOT = 3;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int RCBR = 25;
  public static final int LB = 20;
  public static final int LAND = 17;
  public static final int RETURN = 33;
  public static final int EQUAL = 11;
  public static final int TRUE = 42;
  public static final int NEW = 40;
  public static final int error = 1;
  public static final int RB = 21;
  public static final int LOR = 18;
  public static final int NULL = 44;
  public static final int MOD = 9;
  public static final int BREAK = 37;
  public static final int VOID = 29;
  public static final int GTE = 15;
  public static final int ELSE = 35;
  public static final int WHILE = 36;
  public static final int NEQUAL = 12;
  public static final int CLASS_ID = 48;
  public static final int EXTENDS = 27;
  public static final int STRING = 32;
  public static final int LNEG = 19;
  public static final int FALSE = 43;
  public static final int GT = 13;
  public static final int LENGTH = 41;
}

