
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 01 11:24:57 IST 2016
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 20;
  public static final int LCBR = 6;
  public static final int LTE = 11;
  public static final int UMINUS = 49;
  public static final int INTEGER = 45;
  public static final int SEMI = 43;
  public static final int CONTINUE = 36;
  public static final int INT = 22;
  public static final int MINUS = 18;
  public static final int STATIC = 29;
  public static final int LT = 9;
  public static final int LP = 2;
  public static final int COMMA = 41;
  public static final int CLASS = 39;
  public static final int RP = 3;
  public static final int PLUS = 17;
  public static final int MULTIPLY = 19;
  public static final int QUOTE = 46;
  public static final int ASSIGN = 44;
  public static final int IF = 32;
  public static final int THIS = 27;
  public static final int ID = 47;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int BOOLEAN = 23;
  public static final int RCBR = 7;
  public static final int LB = 4;
  public static final int LAND = 12;
  public static final int RETURN = 31;
  public static final int EQUAL = 14;
  public static final int TRUE = 25;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int RB = 5;
  public static final int LOR = 13;
  public static final int NULL = 40;
  public static final int MOD = 21;
  public static final int BREAK = 35;
  public static final int VOID = 30;
  public static final int GTE = 10;
  public static final int ELSE = 33;
  public static final int WHILE = 34;
  public static final int NEQUAL = 15;
  public static final int CLASS_ID = 48;
  public static final int EXTENDS = 28;
  public static final int STRING = 24;
  public static final int LNEG = 16;
  public static final int FALSE = 26;
  public static final int GT = 8;
  public static final int LENGTH = 38;
}

